# Generated by Django 3.0 on 2021-05-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uiid', models.UUIDField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
