# Generated by Django 3.0 on 2021-05-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210524_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamp',
            old_name='uiid',
            new_name='uuid',
        ),
    ]
